### ISSUE TITLE
Clicking into user/password fields triggers Error: LateInitializationError: Local 'command' has not been initialized.

### ISSUE THREAD

**Issue by oysterpack** [NearHuscarl/flutter_login#187]
**Describe the bug**
`Error: LateInitializationError: Local 'command' has not been initialized.` errors are triggered by text input field events and logged in the background. 

**To Reproduce**
The issue can be reproduced easily when running the **example** project as a webapp, i.e., via `flutter run -d chrome`

**Expected behavior**
The widget still appears to "work", but the logged error messages are concerning. 

**Information (please complete the following information):**
 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (1 available)

**Additional context**
- https://dart.dev/guides/language/language-tour#late-variables

**Comment by jaredbaszler** [comment]
I'm getting the same behavior.  I tried upgrading from v1.1.0 to v2.0.0 but this still existed.  I'm currently running Flutter Web for this project.  For me, this is a project that I stepped away from for 2-3 months and now I'm coming back to it.  So I've upgraded Flutter 2-3 times during that time away.  That is about all that's changed.  Here is the stack trace I'm getting:

```
Error: LateInitializationError: Local 'command' has not been initialized.
    at Object.throw_ [as throw] (http://localhost:51701/dart_sdk.js:5348:11)
    at command$35get (http://localhost:51701/dart_sdk.js:181049:54)
    at _engine.TextEditingChannel.new.handleTextInput (http://localhost:51701/dart_sdk.js:181129:41)
    at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (http://localhost:51701/dart_sdk.js:166451:39)
    at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (http://localhost:51701/dart_sdk.js:166313:33)
    at _DefaultBinaryMessenger.[_sendPlatformMessage] (http://localhost:51701/packages/flutter/src/services/system_channels.dart.lib.js:2195:38)
    at _DefaultBinaryMessenger.send (http://localhost:51701/packages/flutter/src/services/system_channels.dart.lib.js:2239:40)
    at OptionalMethodChannel._invokeMethod (http://localhost:51701/packages/flutter/src/services/system_channels.dart.lib.js:957:50)
    at _invokeMethod.next (<anonymous>)
    at runBody (http://localhost:51701/dart_sdk.js:39250:34)
    at Object._async [as async] (http://localhost:51701/dart_sdk.js:39281:7)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:51701/packages/flutter/src/services/system_channels.dart.lib.js:955:20)
    at OptionalMethodChannel.[_invokeMethod] (http://localhost:51701/packages/flutter/src/services/system_channels.dart.lib.js:1087:34)
    at OptionalMethodChannel.invokeMethod (http://localhost:51701/packages/flutter/src/services/system_channels.dart.lib.js:1065:36)
    at invokeMethod.next (<anonymous>)
    at runBody (http://localhost:51701/dart_sdk.js:39250:34)
    at Object._async [as async] (http://localhost:51701/dart_sdk.js:39281:7)
    at OptionalMethodChannel.invokeMethod (http://localhost:51701/packages/flutter/src/services/system_channels.dart.lib.js:1064:20)
    at text_input.TextInput.__.[_requestAutofill] (http://localhost:51701/packages/flutter/src/services/text_input.dart.lib.js:1373:22)
    at text_input.TextInputConnection.__.requestAutofill (http://localhost:51701/packages/flutter/src/services/text_input.dart.lib.js:1096:55)
    at editable_text.EditableTextState.new.[_openInputConnection] (http://localhost:51701/packages/flutter/src/widgets/widget_span.dart.lib.js:48017:56)
    at editable_text.EditableTextState.new.[_openOrCloseInputConnectionIfNeeded] (http://localhost:51701/packages/flutter/src/widgets/widget_span.dart.lib.js:48039:39)
    at editable_text.EditableTextState.new.[_handleFocusChanged] (http://localhost:51701/packages/flutter/src/widgets/widget_span.dart.lib.js:48260:52)
    at focus_manager.FocusNode.new.notifyListeners (http://localhost:51701/packages/flutter/src/foundation/change_notifier.dart.lib.js:108:41)
    at focus_manager.FocusNode.new.[_notify] (http://localhost:51701/packages/flutter/src/widgets/widget_span.dart.lib.js:51453:12)
    at focus_manager.FocusManager.new.[_applyFocusChange] (http://localhost:51701/packages/flutter/src/widgets/widget_span.dart.lib.js:52240:26)
    at Object._microtaskLoop (http://localhost:51701/dart_sdk.js:39374:13)
    at _startMicrotaskLoop (http://localhost:51701/dart_sdk.js:39380:13)
    at http://localhost:51701/dart_sdk.js:34887:9
```

**Comment by iqmia** [comment]
This error is triggered when the user clicks on any textFormField in the login form.  I'm having the same problem.

**Comment by trevhud** [comment]
Did you guys have any luck with this? I'm getting the same issue

**Comment by i5o** [comment]
Can confirm this still happens.
![image](https://user-images.githubusercontent.com/2650479/125305204-8d9a3500-e304-11eb-8271-8bf1572772de.png)

**Comment by arslandevcrew** [comment]
get same error on chrome

**Comment by Silfalion** [comment]
me too

**Comment by sarbogast** [comment]
Apparently this error is generic in Flutter web: https://github.com/flutter/flutter/issues/83618

It's supposed to have been fixed but apparently the fix hasn't been released yet

**Comment by faradie** [comment]
I'm getting the same issue. Did you guys have any luck with this?

**Comment by semsturgut** [comment]
Same here 😕

**Comment by cbanaspk** [comment]
Still getting same error

**Comment by juliansteenbakker** [comment]
A fix has been merged in flutter and is already present on the master channel of Flutter.
