### ISSUE TITLE
AnimationController.forward() called after AnimationController.dispose()

### ISSUE THREAD

**Issue by risingwolf21** [NearHuscarl/flutter_login#26]
So I have an FirebaseAuth onStatechanged at the beginnig of my Application. When I am logged in I see my HomePage otherwise I go to the LoginScreen wich is implemented with flutter_login. However when I am logged in, I still get an error wich looks like this and is from this package. 
````
√ Built build\app\outputs\apk\debug\app-debug.apk.

[38;5;248m════════ Exception caught by widgets library ═══════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown while finalizing the widget tree:[39;49m
_FlutterLoginState#74227(tickers: tracking 3 tickers) was disposed with an active Ticker.

[38;5;244m_FlutterLoginState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. All Tickers must be disposed before calling super.dispose().[39;49m

[38;5;248mTickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.[39;49m

The offending ticker was: _WidgetTicker(created by _FlutterLoginState#74227(lifecycle state: created, tickers: tracking 0 tickers))
The stack trace when the _WidgetTicker was actually created was:
[38;5;244m#0      new Ticker.<anonymous closure>[39;49m
[38;5;244m#1      new Ticker[39;49m
[38;5;244m#2      new _WidgetTicker[39;49m
[38;5;244m#3      TickerProviderStateMixin.createTicker[39;49m
[38;5;244m#4      new AnimationController[39;49m
[38;5;248m#5      _FlutterLoginState.initState[39;49m
[38;5;244m#6      StatefulElement._firstBuild[39;49m
[38;5;244m#7      ComponentElement.mount[39;49m
[38;5;244m#8      Element.inflateWidget[39;49m
[38;5;244m#9      Element.updateChild[39;49m
[38;5;244m#10     ComponentElement.performRebuild[39;49m
[38;5;244m#11     Element.rebuild[39;49m
[38;5;244m#12     ComponentElement._firstBuild[39;49m
[38;5;244m#13     StatefulElement._firstBuild[39;49m
[38;5;244m#14     ComponentElement.mount[39;49m
[38;5;244m#15     Element.inflateWidget[39;49m
[38;5;244m#16     Element.updateChild[39;49m
[38;5;244m#17     ComponentElement.performRebuild[39;49m
[38;5;244m#18     Element.rebuild[39;49m
[38;5;244m#19     ComponentElement._firstBuild[39;49m
[38;5;244m#20     StatefulElement._firstBuild[39;49m
[38;5;244m#21     ComponentElement.mount[39;49m
[38;5;244m#22     Element.inflateWidget[39;49m
[38;5;244m#23     Element.updateChild[39;49m
[38;5;244m#24     ComponentElement.performRebuild[39;49m
[38;5;244m#25     Element.rebuild[39;49m
[38;5;244m#26     ComponentElement._firstBuild[39;49m
[38;5;244m#27     StatefulElement._firstBuild[39;49m
[38;5;244m#28     ComponentElement.mount[39;49m
[38;5;244m#29     Element.inflateWidget[39;49m
[38;5;244m#30     Element.updateChild[39;49m
[38;5;244m#31     SingleChildRenderObjectElement.mount[39;49m
[38;5;244m#32     Element.inflateWidget[39;49m
[38;5;244m#33     Element.updateChild[39;49m
[38;5;244m#34     ComponentElement.performRebuild[39;49m
[38;5;244m#35     Element.rebuild[39;49m
[38;5;244m#36     ComponentElement._firstBuild[39;49m
[38;5;244m#37     ComponentElement.mount[39;49m
[38;5;244m#38     Element.inflateWidget[39;49m
[38;5;244m#39     Element.updateChild[39;49m
[38;5;244m#40     SingleChildRenderObjectElement.mount[39;49m
[38;5;244m#41     Element.inflateWidget[39;49m
[38;5;244m#42     Element.updateChild[39;49m
[38;5;244m#43     SingleChildRenderObjectElement.mount[39;49m
[38;5;244m#44     Element.inflateWidget[39;49m
[38;5;244m#45     Element.updateChild[39;49m
[38;5;244m#46     ComponentElement.performRebuild[39;49m
[38;5;244m#47     Element.rebuild[39;49m
[38;5;244m#48     ComponentElement._firstBuild[39;49m
[38;5;244m#49     StatefulElement._firstBuild[39;49m
[38;5;244m#50     ComponentElement.mount[39;49m
[38;5;244m#51     Element.inflateWidget[39;49m
[38;5;244m#52     Element.updateChild[39;49m
[38;5;244m#53     SingleChildRenderObjectElement.mount[39;49m
[38;5;244m#54     Element.inflateWidget[39;49m
[38;5;244m#55     Element.updateChild[39;49m
[38;5;244m#56     SingleChildRenderObjectElement.mount[39;49m
[38;5;244m#57     Element.inflateWidget[39;49m
[38;5;244m#58     Element.updateChild[39;49m
[38;5;244m#59     ComponentElement.performRebuild[39;49m
[38;5;244m#60     Element.rebuild[39;49m
[38;5;244m#61     ComponentElement._firstBuild[39;49m
[38;5;244m#62     StatefulElement._firstBuild[39;49m
[38;5;244m#63     ComponentElement.mount[39;49m
[38;5;244m#64     Element.inflateWidget[39;49m
[38;5;244m#65     Element.updateChild[39;49m
[38;5;244m#66     ComponentElement.performRebuild[39;49m
[38;5;244m#67     Element.rebuild[39;49m
[38;5;244m#68     ComponentElement._firstBuild[39;49m
[38;5;244m#69     ComponentElement.mount[39;49m
[38;5;244m#70     Element.inflateWidget[39;49m
[38;5;244m#71     Element.updateChild[39;49m
[38;5;244m#72     ComponentElement.performRebuild[39;49m
[38;5;244m#73     Element.rebuild[39;49m
[38;5;244m#74     ComponentElement._firstBuild[39;49m
[38;5;244m#75     StatefulElement._firstBuild[39;49m
[38;5;244m#76     ComponentElement.mount[39;49m
[38;5;244m#77     Element.inflateWidget[39;49m
[38;5;244m#78     Element.updateChild[39;49m
[38;5;244m#79     SingleChildRenderObjectElement.mount[39;49m
[38;5;244m#80     Element.inflateWidget[39;49m
[38;5;244m#81     Element.updateChild[39;49m
[38;5;244m#82     ComponentElement.performRebuild[39;49m
[38;5;244m#83     Element.rebuild[39;49m
[38;5;244m#84     ComponentElement._firstBuild[39;49m
[38;5;244m#85     ComponentElement.mount[39;49m
[38;5;244m#86     Element.inflateWidget[39;49m
[38;5;244m#87     Element.updateChild[39;49m
[38;5;244m#88     SingleChildRenderObjectElement.mount[39;49m
[38;5;244m#89     Element.inflateWidget[39;49m
[38;5;244m#90     Element.updateChild[39;49m
[38;5;244m#91     ComponentElement.performRebuild[39;49m
[38;5;244m#92     Element.rebuild[39;49m
[38;5;244m#93     ComponentElement._firstBuild[39;49m
[38;5;244m#94     StatefulElement._firstBuild[39;49m
[38;5;244m#95     ComponentElement.mount[39;49m
[38;5;244m#96     Element.inflateWidget[39;49m
[38;5;244m#97     Element.updateChild[39;49m
[38;5;244m#98     ComponentElement.performRebuild[39;49m
[38;5;244m#99     Element.rebuild[39;49m
[38;5;244m#100    ComponentElement._firstBuild[39;49m
[38;5;244m#101    ComponentElement.mount[39;49m
[38;5;244m#102    Element.inflateWidget[39;49m
[38;5;244m#103    Element.updateChild[39;49m
[38;5;244m#104    SingleChildRenderObjectElement.mount[39;49m
[38;5;244m#105    Element.inflateWidget[39;49m
[38;5;244m#106    Element.updateChild[39;49m
[38;5;244m#107    ComponentElement.performRebuild[39;49m
[38;5;244m#108    Element.rebuild[39;49m
[38;5;244m#109    ComponentElement._firstBuild[39;49m
[38;5;244m#110    ComponentElement.mount[39;49m
[38;5;244m#111    Element.inflateWidget[39;49m
[38;5;244m#112    Element.updateChild[39;49m
[38;5;244m#113    ComponentElement.performRebuild[39;49m
[38;5;244m#114    Element.rebuild[39;49m
[38;5;244m#115    ComponentElement._firstBuild[39;49m
[38;5;244m#116    StatefulElement._firstBuild[39;49m
[38;5;244m#117    ComponentElement.mount[39;49m
[38;5;244m#118    Element.inflateWidget[39;49m
[38;5;244m#119    Element.updateChild[39;49m
[38;5;244m#120    ComponentElement.performRebuild[39;49m
[38;5;244m#121    Element.rebuild[39;49m
[38;5;244m#122    ComponentElement._firstBuild[39;49m
[38;5;244m#123    StatefulElement._firstBuild[39;49m
[38;5;244m#124    ComponentElement.mount[39;49m
[38;5;244m#125    Element.inflateWidget[39;49m
[38;5;244m#126    MultiChildRenderObjectElement.mount[39;49m
[38;5;244m#127    Element.inflateWidget[39;49m
[38;5;244m#128    Element.updateChild[39;49m
[38;5;244m#129    _TheatreElement.mount[39;49m
[38;5;244m#130    Element.inflateWidget[39;49m
[38;5;244m#131    Element.updateChild[39;49m
[38;5;244m#132    ComponentElement.performRebuild[39;49m
[38;5;244m#133    Element.rebuild[39;49m
[38;5;244m#134    ComponentElement._firstBuild[39;49m
[38;5;244m#135    StatefulElement._firstBuild[39;49m
[38;5;244m#136    ComponentElement.mount[39;49m
[38;5;244m#137    Element.inflateWidget[39;49m
[38;5;244m#138    Element.updateChild[39;49m
[38;5;244m#139    ComponentElement.performRebuild[39;49m
[38;5;244m#140    Element.rebuild[39;49m
[38;5;244m#141    ComponentElement._firstBuild[39;49m
[38;5;244m#142    ComponentElement.mount[39;49m
[38;5;244m#143    Element.inflateWidget[39;49m
[38;5;244m#144    Element.updateChild[39;49m
[38;5;244m#145    SingleChildRenderObjectElement.mount[39;49m
[38;5;244m#146    Element.inflateWidget[39;49m
[38;5;244m#147    Element.updateChild[39;49m
[38;5;244m#148    ComponentElement.performRebuild[39;49m
[38;5;244m#149    Element.rebuild[39;49m
[38;5;244m#150    ComponentElement._firstBuild[39;49m
[38;5;244m#151    StatefulElement._firstBuild[39;49m
[38;5;244m#152    ComponentElement.mount[39;49m
[38;5;244m#153    Element.inflateWidget[39;49m
[38;5;244m#154    Element.updateChild[39;49m
[38;5;244m#155    SingleChildRenderObjectElement.mount[39;49m
[38;5;244m#156    Element.inflateWidget[39;49m
[38;5;244m#157    Element.updateChild[39;49m
[38;5;244m#158    SingleChildRenderObjectElement.mount[39;49m
[38;5;244m#159    Element.inflateWidget[39;49m
[38;5;244m#160    Element.updateChild[39;49m
[38;5;244m#161    ComponentElement.performRebuild[39;49m
[38;5;244m#162    Element.rebuild[39;49m
[38;5;244m#163    ComponentElement._firstBuild[39;49m
[38;5;244m#164    ComponentElement.mount[39;49m
[38;5;244m#165    Element.inflateWidget[39;49m
[38;5;244m#166    Element.updateChild[39;49m
[38;5;244m#167    ComponentElement.performRebuild[39;49m
[38;5;244m#168    Element.rebuild[39;49m
[38;5;244m#169    ComponentElement._firstBuild[39;49m
[38;5;244m#170    StatefulElement._firstBuild[39;49m
[38;5;244m#171    ComponentElement.mount[39;49m
[38;5;244m#172    Element.inflateWidget[39;49m
[38;5;244m#173    Element.updateChild[39;49m
[38;5;244m#174    ComponentElement.performRebuild[39;49m
[38;5;244m#175    Element.rebuild[39;49m
[38;5;244m#176    ComponentElement._firstBuild[39;49m
[38;5;244m#177    ComponentElement.mount[39;49m
[38;5;244m#178    Element.inflateWidget[39;49m
[38;5;244m#179    Element.updateChild[39;49m
[38;5;244m#180    ComponentElement.performRebuild[39;49m
[38;5;244m#181    Element.rebuild[39;49m
[38;5;244m#182    ComponentElement._firstBuild[39;49m
[38;5;244m#183    ComponentElement.mount[39;49m
[38;5;244m#184    Element.inflateWidget[39;49m
[38;5;244m#185    Element.updateChild[39;49m
[38;5;244m#186    ComponentElement.performRebuild[39;49m
[38;5;244m#187    Element.rebuild[39;49m
[38;5;244m#188    ComponentElement._firstBuild[39;49m
[38;5;244m#189    ComponentElement.mount[39;49m
[38;5;244m#190    Element.inflateWidget[39;49m
[38;5;244m#191    Element.updateChild[39;49m
[38;5;244m#192    ComponentElement.performRebuild[39;49m
[38;5;244m#193    Element.rebuild[39;49m
[38;5;244m#194    ComponentElement._firstBuild[39;49m
[38;5;244m#195    ComponentElement.mount[39;49m
[38;5;244m#196    Element.inflateWidget[39;49m
[38;5;244m#197    Element.updateChild[39;49m
[38;5;244m#198    ComponentElement.performRebuild[39;49m
[38;5;244m#199    Element.rebuild[39;49m
[38;5;244m#200    ComponentElement._firstBuild[39;49m
[38;5;244m#201    ComponentElement.mount[39;49m
[38;5;244m#202    Element.inflateWidget[39;49m
[38;5;244m#203    Element.updateChild[39;49m
[38;5;244m#204    ComponentElement.performRebuild[39;49m
[38;5;244m#205    Element.rebuild[39;49m
[38;5;244m#206    ComponentElement._firstBuild[39;49m
[38;5;244m#207    ComponentElement.mount[39;49m
[38;5;244m#208    Element.inflateWidget[39;49m
[38;5;244m#209    Element.updateChild[39;49m
[38;5;244m#210    ComponentElement.performRebuild[39;49m
[38;5;244m#211    Element.rebuild[39;49m
[38;5;244m#212    ComponentElement._firstBuild[39;49m
[38;5;244m#213    StatefulElement._firstBuild[39;49m
[38;5;244m#214    ComponentElement.mount[39;49m
[38;5;244m#215    Element.inflateWidget[39;49m
[38;5;244m#216    Element.updateChild[39;49m
[38;5;244m#217    ComponentElement.performRebuild[39;49m
[38;5;244m#218    Element.rebuild[39;49m
[38;5;244m#219    ComponentElement._firstBuild[39;49m
[38;5;244m#220    ComponentElement.mount[39;49m
[38;5;244m#221    Element.inflateWidget[39;49m
[38;5;244m#222    Element.updateChild[39;49m
[38;5;244m#223    ComponentElement.performRebuild[39;49m
[38;5;244m#224    Element.rebuild[39;49m
[38;5;244m#225    ComponentElement._firstBuild[39;49m
[38;5;244m#226    ComponentElement.mount[39;49m
[38;5;244m#227    Element.inflateWidget[39;49m
[38;5;244m#228    Element.updateChild[39;49m
[38;5;244m#229    ComponentElement.performRebuild[39;49m
[38;5;244m#230    Element.rebuild[39;49m
[38;5;244m#231    ComponentElement._firstBuild[39;49m
[38;5;244m#232    ComponentElement.mount[39;49m
[38;5;244m#233    Element.inflateWidget[39;49m
[38;5;244m#234    Element.updateChild[39;49m
[38;5;244m#235    ComponentElement.performRebuild[39;49m
[38;5;244m#236    Element.rebuild[39;49m
[38;5;244m#237    ComponentElement._firstBuild[39;49m
[38;5;244m#238    ComponentElement.mount[39;49m
[38;5;244m#239    Element.inflateWidget[39;49m
[38;5;244m#240    Element.updateChild[39;49m
[38;5;244m#241    ComponentElement.performRebuild[39;49m
[38;5;244m#242    Element.rebuild[39;49m
[38;5;244m#243    ComponentElement._firstBuild[39;49m
[38;5;244m#244    ComponentElement.mount[39;49m
[38;5;244m#245    Element.inflateWidget[39;49m
[38;5;244m#246    Element.updateChild[39;49m
[38;5;244m#247    SingleChildRenderObjectElement.mount[39;49m
[38;5;244m#248    Element.inflateWidget[39;49m
[38;5;244m#249    Element.updateChild[39;49m
[38;5;244m#250    ComponentElement.performRebuild[39;49m
[38;5;244m#251    Element.rebuild[39;49m
[38;5;244m#252    ComponentElement._firstBuild[39;49m
[38;5;244m#253    StatefulElement._firstBuild[39;49m
[38;5;244m#254    ComponentElement.mount[39;49m
[38;5;244m#255    Element.inflateWidget[39;49m
[38;5;244m#256    Element.updateChild[39;49m
[38;5;244m#257    ComponentElement.performRebuild[39;49m
[38;5;244m#258    Element.rebuild[39;49m
[38;5;244m#259    ComponentElement._firstBuild[39;49m
[38;5;244m#260    ComponentElement.mount[39;49m
[38;5;244m#261    Element.inflateWidget[39;49m
[38;5;244m#262    Element.updateChild[39;49m
[38;5;244m#263    ComponentElement.performRebuild[39;49m
[38;5;244m#264    Element.rebuild[39;49m
[38;5;244m#265    ComponentElement._firstBuild[39;49m
[38;5;244m#266    StatefulElement._firstBuild[39;49m
[38;5;244m#267    ComponentElement.mount[39;49m
[38;5;244m#268    Element.inflateWidget[39;49m
[38;5;244m#269    Element.updateChild[39;49m
[38;5;244m#270    ComponentElement.performRebuild[39;49m
[38;5;244m#271    Element.rebuild[39;49m
[38;5;244m#272    ComponentElement._firstBuild[39;49m
[38;5;244m#273    ComponentElement.mount[39;49m
[38;5;244m#274    Element.inflateWidget[39;49m
[38;5;244m#275    Element.updateChild[39;49m
[38;5;244m#276    ComponentElement.performRebuild[39;49m
[38;5;244m#277    Element.rebuild[39;49m
[38;5;244m#278    ComponentElement._firstBuild[39;49m
[38;5;244m#279    ComponentElement.mount[39;49m
[38;5;244m#280    Element.inflateWidget[39;49m
[38;5;244m#281    Element.updateChild[39;49m
[38;5;244m#282    ComponentElement.performRebuild[39;49m
[38;5;244m#283    Element.rebuild[39;49m
[38;5;244m#284    ComponentElement._firstBuild[39;49m
[38;5;244m#285    ComponentElement.mount[39;49m
[38;5;244m#286    Element.inflateWidget[39;49m
[38;5;244m#287    Element.updateChild[39;49m
[38;5;244m#288    SingleChildRenderObjectElement.mount[39;49m
[38;5;244m#289    Element.inflateWidget[39;49m
[38;5;244m#290    Element.updateChild[39;49m
[38;5;244m#291    ComponentElement.performRebuild[39;49m
[38;5;244m#292    Element.rebuild[39;49m
[38;5;244m#293    ComponentElement._firstBuild[39;49m
[38;5;244m#294    ComponentElement.mount[39;49m
[38;5;244m#295    Element.inflateWidget[39;49m
[38;5;244m#296    Element.updateChild[39;49m
[38;5;244m#297    ComponentElement.performRebuild[39;49m
[38;5;244m#298    Element.rebuild[39;49m
[38;5;244m#299    ComponentElement._firstBuild[39;49m
[38;5;244m#300    StatefulElement._firstBuild[39;49m
[38;5;244m#301    ComponentElement.mount[39;49m
[38;5;244m#302    Element.inflateWidget[39;49m
[38;5;244m#303    Element.updateChild[39;49m
[38;5;244m#304    ComponentElement.performRebuild[39;49m
[38;5;244m#305    Element.rebuild[39;49m
[38;5;244m#306    ComponentElement._firstBuild[39;49m
[38;5;244m#307    StatefulElement._firstBuild[39;49m
[38;5;244m#308    ComponentElement.mount[39;49m
[38;5;244m#309    Element.inflateWidget[39;49m
[38;5;244m#310    Element.updateChild[39;49m
[38;5;244m#311    ComponentElement.performRebuild[39;49m
[38;5;244m#312    Element.rebuild[39;49m
[38;5;244m#313    ComponentElement._firstBuild[39;49m
[38;5;244m#314    StatefulElement._firstBuild[39;49m
[38;5;244m#315    ComponentElement.mount[39;49m
[38;5;244m#316    Element.inflateWidget[39;49m
[38;5;244m#317    Element.updateChild[39;49m
[38;5;244m#318    ComponentElement.performRebuild[39;49m
[38;5;244m#319    Element.rebuild[39;49m
[38;5;244m#320    ComponentElement._firstBuild[39;49m
[38;5;244m#321    ComponentElement.mount[39;49m
[38;5;244m#322    Element.inflateWidget[39;49m
[38;5;244m#323    Element.updateChild[39;49m
[38;5;244m#324    ComponentElement.performRebuild[39;49m
[38;5;244m#325    Element.rebuild[39;49m
[38;5;244m#326    ComponentElement._firstBuild[39;49m
[38;5;244m#327    StatefulElement._firstBuild[39;49m
[38;5;244m#328    ComponentElement.mount[39;49m
[38;5;244m#329    Element.inflateWidget[39;49m
[38;5;244m#330    Element.updateChild[39;49m
[38;5;244m#331    RenderObjectToWidgetElement._rebuild[39;49m
[38;5;244m#332    RenderObjectToWidgetElement.mount[39;49m
[38;5;244m#333    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>[39;49m
[38;5;244m#334    BuildOwner.buildScope[39;49m
[38;5;244m#335    RenderObjectToWidgetAdapter.attachToRenderTree[39;49m
[38;5;244m#336    WidgetsBinding.attachRootWidget[39;49m
[38;5;244m#337    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure>[39;49m
[38;5;244m#346    _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:384:19)[39;49m
[38;5;244m#347    _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:418:5)[39;49m
[38;5;244m#348    _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:174:12)[39;49m
(elided 8 frames from package dart:async and package dart:async-patch)

[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#0      TickerProviderStateMixin.dispose.<anonymous closure>[39;49m
[38;5;244m#1      TickerProviderStateMixin.dispose[39;49m
[38;5;248m#2      _FlutterLoginState.dispose[39;49m
[38;5;244m#3      StatefulElement.unmount[39;49m
[38;5;244m#4      _InactiveElements._unmount[39;49m
[38;5;244m...[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

[38;5;248m════════ Exception caught by animation library ═════════════════════════════════[39;49m
AnimationController.forward() called after AnimationController.dispose()
AnimationController methods should not be used after calling dispose.
'package:flutter/src/animation/animation_controller.dart':
Failed assertion: line 451 pos 7: '_ticker != null'
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

````

**Comment by JulienT-FL** [comment]
Same issue for me with Firebase auth also. Did you find any solution?

**Comment by khalifa007** [comment]
Same with me.

**Comment by sarbogast** [comment]
Same issue.

**Comment by taracell** [comment]
I have had this same problem and fixed it by changing all void dispose() functions within auth_card.dart file to use the super.dispose() method like dart wants it.  Example:
```dart
  @override
  void dispose() {
    _formLoadingController.dispose();
    _pageController.dispose();
    _routeTransitionController.dispose();
    super.dispose();
  }```

**Comment by aweiand** [comment]
Any fix?

**Comment by surister** [comment]
> Any fix?

Have you read the comment above?

**Comment by aweiand** [comment]
> > Any fix?
> 
> Have you read the comment above?

Yes, however it's a trick to fix the problem, not a change in the flutter_login package. 
In other hand, I cant't understand where put the code write from @taracell .... its necessary to create a new auth_card.dart file in my project and put this? Or copy all the files from package and edit only this?
Apparently, the original code from package have this code...

**Comment by taracell** [comment]
> > > Any fix?
> 
> > 
> 
> > Have you read the comment above?
> 
> 
> 
> Yes, however it's a trick to fix the problem, not a change in the flutter_login package. 
> 
> In other hand, I cant't understand where put the code write from @taracell .... its necessary to create a new auth_card.dart file in my project and put this? Or copy all the files from package and edit only this?
> 
> Apparently, the original code from package have this code...
> 
> 
> 
> 
> 
> 
> 
> 

This was 11 months ago when I changed what was downloaded on my machine within the package to make it work. I'm not using this package anymore so I don't have a fix for you. Sorry.
