### ISSUE TITLE
Error when returning null from `onLogin`

### ISSUE THREAD

**Issue by thechubbypanda** [NearHuscarl/flutter_login#73]
I keep getting the following error:

```
E/flutter (20871): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'call' was called on null.
E/flutter (20871): Receiver: null
E/flutter (20871): Tried calling: call()
E/flutter (20871): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (20871): #1      AuthCardState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter_login/src/widgets/auth_card.dart:294:50)
E/flutter (20871): #2      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (20871): #3      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (20871): #4      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter (20871): #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (20871): #6      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (20871): #7      Future._complete (dart:async/future_impl.dart:516:7)
E/flutter (20871): #8      Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:466:16)
E/flutter (20871): #9      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (20871): #10     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (20871): #11     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter (20871): #12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (20871): #13     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (20871): #14     Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter (20871): #15     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
E/flutter (20871): #16     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (20871): #17     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (20871): #18     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (20871): #19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (20871): #20     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter (20871): #21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
```

There appears to be no issues with the function but I'm sure this isn't supposed to happen.

**To Reproduce**
1. Create the following flutter app: 
```
import 'package:flutter/material.dart';
import 'package:flutter_login/flutter_login.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: FlutterLogin(
        onLogin: (data) {
          //Navigator.pop(context);
          return null;
        },
        onSignup: (data) {
          return null;
        },
        onRecoverPassword: (data) {
          return null;
        },
      ),
    );
  }
}
```
2. Fill in the fields so they validate
3. Press login

**Expected behavior**
The error shouldn't appear.

**Information:**
 - Device: Samsung Note 9
 - Platform: Mobile
 - Flutter version: 1.17.5
 - Package version: 1.0.14

**Comment by juliansteenbakker** [comment]
Can you please try again with version 1.0.15. Feel free to comment if you still have this issue.
