### ISSUE TITLE
Running any test fails

### ISSUE THREAD

**Issue by evanblasband** [NearHuscarl/flutter_login#77]
**Describe the bug**
Any time i run a test it throws an error in the flutter test framework, no matter what test I run.  I am trying to implement CI but can't get any tests to run.

**To Reproduce**
For example I tried running this simple test:
```
testWidgets('Loading default login and making sure all fields are found',
      (WidgetTester tester) async {
    // Setup
    await tester.pumpWidget(defaultFlutterLogin());
    await tester.pumpAndSettle(loadingAnimationDuration);

    // test
    expect(logoWidget(tester), findsOneWidget);

  });
```

**Expected behavior**
I did not change any of the utils and would have expected this to pass.  However the following is what was produced.

**Error**
```
Loading default login and making sure all fields are found:

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
Expected  to match RegExp: pattern=^(.+) (\d+):(\d+)\s+(.+)$ flags=.
'package:flutter/src/foundation/stack_frame.dart':
Failed assertion: line 115 pos 12: 'match != null'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
#2      StackFrame._parseWebDebugFrame (package:flutter/src/foundation/stack_frame.dart:115:12)
#3      StackFrame._parseWebFrame (package:flutter/src/foundation/stack_frame.dart:101:14)
#4      StackFrame.fromStackTraceLine (package:flutter/src/foundation/stack_frame.dart:202:14)
#5      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#6      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#7      SkipWhileIterator.moveNext (dart:_internal/iterable.dart:676:24)
#8      new List.from (dart:core-patch/array_patch.dart:50:19)
#9      new List.of (dart:core-patch/array_patch.dart:68:17)
#10     Iterable.toList (dart:core/iterable.dart:404:12)
#11     StackFrame.fromStackString (package:flutter/src/foundation/stack_frame.dart:96:10)
#12     FlutterError.defaultStackFilter (package:flutter/src/foundation/assertions.dart:1000:54)
#13     TestWidgetsFlutterBinding._runTest.handleUncaughtError.<anonymous closure> (package:flutter_test/src/binding.dart:709:31)
#14     DiagnosticsStackTrace._applyStackFilter (package:flutter/src/foundation/assertions.dart:1170:43)
#15     new DiagnosticsStackTrace (package:flutter/src/foundation/assertions.dart:1145:17)
#16     FlutterErrorDetails.debugFillProperties (package:flutter/src/foundation/assertions.dart:680:22)
#17     DiagnosticableNode.builder.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:2944:18)
#18     DiagnosticableNode.builder (package:flutter/src/foundation/diagnostics.dart:2947:8)
#19     _FlutterErrorDetailsNode.builder (package:flutter/src/foundation/assertions.dart:1192:55)
#20     DiagnosticableNode.getProperties (package:flutter/src/foundation/diagnostics.dart:2961:105)
#21     TextTreeRenderer._debugRender (package:flutter/src/foundation/diagnostics.dart:1250:63)
#22     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1128:14)
#23     FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:955:11)
#24     TestWidgetsFlutterBinding._runTest.<anonymous closure> (package:flutter_test/src/binding.dart:620:24)
#25     FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1087:14)
#26     TestWidgetsFlutterBinding._runTest.handleUncaughtError (package:flutter_test/src/binding.dart:703:20)
#27     TestWidgetsFlutterBinding._runTest.<anonymous closure> (package:flutter_test/src/binding.dart:727:28)
#38     FakeTimer._fire (package:fake_async/fake_async.dart:315:16)
#39     FakeAsync._fireTimersWhile (package:fake_async/fake_async.dart:239:13)
#40     FakeAsync.elapse (package:fake_async/fake_async.dart:137:5)
#41     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:920:27)
#44     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#45     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:916:27)
#46     WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:563:23)
#47     WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:558:39)
#50     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#51     WidgetTester.pumpAndSettle (package:flutter_test/src/widget_tester.dart:558:27)
#52     main.<anonymous closure> (file:///Users/evanblasband/allthenticate/apps/flutter/flutter_login-1.0.14-hijacked/test/flutter_login_test.dart:38:18)
#63     FakeAsync.flushMicrotasks (package:fake_async/fake_async.dart:192:32)
#64     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1149:17)
#65     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1137:35)
<asynchronous suspension>
#81     AuthCardState.initState (file:///Users/evanblasband/allthenticate/apps/flutter/flutter_login-1.0.14-hijacked/lib/src/widgets/auth_card.dart:125:5)
#82     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4684:58)
#83     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
...     Normal element mounting (7 frames)
#90     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#91     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
...     Normal element mounting (127 frames)
#218    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#219    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
...     Normal element mounting (19 frames)
#238    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#239    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
...     Normal element mounting (71 frames)
#310    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#311    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#312    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#313    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:397:11)
#314    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#315    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#316    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
...     Normal element mounting (7 frames)
#323    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
...     Normal element mounting (7 frames)
#330    _NestedHookElement.mount (package:nested/nested.dart:188:11)
#331    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#332    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#333    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#334    _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:397:11)
#335    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#336    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#337    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
...     Normal element mounting (7 frames)
#344    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
...     Normal element mounting (7 frames)
#351    _NestedHookElement.mount (package:nested/nested.dart:188:11)
...     Normal element mounting (7 frames)
#358    SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
...     Normal element mounting (140 frames)
#498    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#499    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
...     Normal element mounting (267 frames)
#766    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#767    Element.updateChild (package:flutter/src/widgets/framework.dart:3255:20)
#768    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1174:16)
#769    RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1152:5)
#770    RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1166:7)
#771    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#772    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
#773    AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1056:18)
#774    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#775    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#776    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
#777    AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:929:9)
#780    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#781    AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:916:27)
#782    WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:462:22)
#785    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#786    WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:459:27)
#787    main.<anonymous closure> (file:///Users/evanblasband/allthenticate/apps/flutter/flutter_login-1.0.14-hijacked/test/flutter_login_test.dart:37:18)
#788    main.<anonymous closure> (file:///Users/evanblasband/allthenticate/apps/flutter/flutter_login-1.0.14-hijacked/test/flutter_login_test.dart:35:7)
#789    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
#800    FakeAsync.flushMicrotasks (package:fake_async/fake_async.dart:192:32)
#801    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1149:17)
#802    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1137:35)
(elided 70 frames from class _AssertionError, dart:async, and package:stack_trace)

The test description was:
  Loading default login and making sure all fields are found
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown:
Multiple exceptions (3) were detected during the running of the current test, and at least one was
unexpected.
════════════════════════════════════════════════════════════════════════════════════════════════════
ERROR: Test failed. See exception logs above.
The test description was: Loading default login and making sure all fields are found

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following StateError was thrown running a test (but after the test had completed):
Bad state: No element

When the exception was thrown, this was the stack:
#0      Iterable.single (dart:core/iterable.dart:558:25)
#1      WidgetController.widget (package:flutter_test/src/controller.dart:65:30)
#2      logoWidget (file:///Users/evanblasband/allthenticate/apps/flutter/flutter_login-1.0.14-hijacked/test/utils.dart:113:17)
#3      main.<anonymous closure> (file:///Users/evanblasband/allthenticate/apps/flutter/flutter_login-1.0.14-hijacked/test/flutter_login_test.dart:41:12)
<asynchronous suspension>
#4      main.<anonymous closure> (file:///Users/evanblasband/allthenticate/apps/flutter/flutter_login-1.0.14-hijacked/test/flutter_login_test.dart)
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
<asynchronous suspension>
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#7      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:752:19)
<asynchronous suspension>
#10     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:732:14)
#11     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1133:24)
#12     FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:177:54)
#17     withClock (package:clock/src/default.dart:46:10)
#18     FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:177:22)
#23     FakeAsync.run (package:fake_async/fake_async.dart:177:7)
#24     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1130:15)
#25     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:137:24)
#26     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:171:19)
<asynchronous suspension>
#27     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#32     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:13)
#33     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:235:15)
#38     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:232:5)
#39     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:388:17)
<asynchronous suspension>
#40     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
#45     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:374:9)
#46     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:420:15)
#47     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:373:7)
#54     Invoker._onRun (package:test_api/src/backend/invoker.dart:372:11)
#55     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:152:11)
#56     RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/remote_listener.dart:259:16)
#61     RemoteListener._runLiveTest (package:test_api/src/remote_listener.dart:258:5)
#62     RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/remote_listener.dart:211:7)
#80     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:124:12)
#81     new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#115    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#123    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#124    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#134    _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
#143    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
#144    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
(elided 108 frames from dart:async and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Information (please complete the following information):**
 - Flutter version: 
```
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (11 days ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1
```
 - Package version: 1.0.14

**Additional context**
Error was also produced in previous version of flutter

**Comment by evanblasband** [comment]
wrapping the pumpWidget in a run.async ended up fixing the issue for me and I am able to write and run tests.
```
await tester.runAsync(() async {
      await tester.pumpWidgetdefaultLogin());
    });
await tester.pumpAndSettle(loadingAnimationDuration);
```
